### ISSUE TITLE
CCcorrect error

### ISSUE THREAD

**Issue by haoger** [dgrun/RaceID3_StemID2#1]
Hi,
This was my data:
scRNAseq data：42 cells x 12000 genes；
vset included two vectors : gCC(24 genes) and gCP(116 genes);

When I run the command:
>CCcorrect(sc@fdata,vset=vset,CGenes=NULL,ccor=.4,nComp=NULL,pvalue=.05,quant=.01,mode="pca")
the error occurred:
 ```
Traceback：
3. stop("all entries of 'x' must be nonnegative and finite") 
2. fisher.test(matrix(c(ncol(y) - length(nq), length(nq), length(m) - 
    length(nqm), length(nqm)), ncol = 2), alternative = "g") at E:\20180122desktop\FateID\RaceID3_StemID2-master\RaceID3_StemID2_class.R#1023
1. CCcorrect(sc@fdata, vset = vset, CGenes = NULL, ccor = 0.4, nComp = NULL, 
    pvalue = 0.05, quant = 0.01, mode = "pca") 
```
This error may be related with fisher.test in the CCcorrect function. Can you tell me how can I solve this problem?

I'm Looking forward to your reply.

**Comment by dgrun** [comment]
I think this error occurred because of a NULL argument to Fisher's test. Since I don't know your dataset I'm not really sure, but I tried to implement a bugfix. Please let me know if it work now.

Best wishes,
Domnic
