### ISSUE TITLE
Error in running RaceID::CCcorrect with "ica"

### ISSUE THREAD

**Issue by mkrzak** [dgrun/RaceID3_StemID2#2]
Dear authors,

I am running ascend function CCcorrect with "ica" dimension reduction as follows:
scs <- SCseq(data.frame(data.matrix))
scs <- RaceID::filterdata(scs, minexpr = 5, minnumber = 1)
RaceID::CCcorrect(scs, mode="ica", dimR=TRUE)

and I am getting the following error:

Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

With PCA the error doesn't occur. Do you have some suggestion what can be wrong?

Best,
Monika

**Comment by dgrun** [comment]
Dear Monika,

I think this is an issue regarding the RaceID3_StemID2_package repository, not the old scripts for the algorithm in this repository. I could reproduce this error with the RaceID package and fixed it. The updated version of the package is available at the RaceID3_StemID2_package repository. It was also uploaded to CRAN and approval is pending.
The CCcorrect function should work now also in the "ica" mode, but to my experience the "pca" mode generally works better.

Best wishes,
Dominic
