### ISSUE TITLE
How do you account for mitochondrial genes in the RaceID2_StemID algorithm?

### ISSUE THREAD

**Issue by charlesgwellem** [dgrun/RaceID3_StemID2#3]
1)	In the RaceID2 algorithm, is there a possibility to account for mitochondrial genes (whose high counts often indicate cell death)? Or is it even necessary for this algorithm?
2)	Is there a possibility to enhance the boundaries of my clusters on the tsne plots of the RaceID2 algorithm? With RaceID2 I am able to see the two clusters previously identified with Seurat  but I wish to see a clearer demarcation on the tsne plot.
3)	Markers of my fibrotic cluster such as Il1rl1 show an overlap between the two clusters when I try to visualize the expression of this gene with RaceID2. The overlap is so strong that I can almost not differentiate between the two clusters again. Is there a possibility for me to improve this? In Seurat the demarcations are somehow clearer and I wish to have a comparably similar feature on RaceID2 for publication purposes.

**Comment by dgrun** [comment]
I'm closing this issue after discussing with you alternative approaches using the novel RaceID3 package.
